### ISSUE TITLE
OSError: [Errno 110] ETIMEDOUT PICO W

### ISSUE THREAD

**Issue by mfraser** [KitronikLtd/Kitronik-Pico-Robotics-Board-MicroPython#11]
Trying to get this working on a PICO W with MicroPython:
```MicroPython v1.22.2 on 2024-02-22; Raspberry Pi Pico W with RP2040```

I just get errorno 110.

```
>>> import PicoRobotics
>>> board = PicoRobotics.KitronikPicoRobotics()
>>> board.motorOn(1,"f",100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PicoRobotics.py", line 118, in motorOn
OSError: [Errno 110] ETIMEDOUT
```

**Comment by mfraser** [comment]
Forgot to add power to the board.
